# Generated by Django 5.0.1 on 2024-03-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biens',
            name='categories',
            field=models.CharField(choices=[('immobiliers', 'Immobiliers'), ('vehicules', 'Véhicules'), ('equipements', 'Équipements'), ('services', 'Services'), ('vetements', 'vetements'), ('autres', 'Autres')], max_length=20),
        ),
    ]
