# Generated by Django 5.0.1 on 2024-02-27 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='date_paiement',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='montant',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reservation',
        ),
        migrations.AddField(
            model_name='payment',
            name='bien',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.biens'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='locataire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='biens',
            name='categories',
            field=models.CharField(choices=[('immobiliers', 'Immobiliers'), ('vehicules', 'Véhicules'), ('equipements', 'Équipements'), ('services', 'Services'), ('autres', 'Autres')], max_length=20),
        ),
    ]
