# Generated by Django 5.0.1 on 2024-02-27 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_created_at_payment_date_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='debut_reservation',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='fin_reservation',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
