# Generated by Django 5.0.1 on 2024-02-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_biens_image_facultative_4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='prix',
        ),
    ]
