# Generated by Django 5.0.1 on 2024-03-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_biens_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='numero_tel',
            field=models.IntegerField(),
        ),
    ]
