# Generated by Django 5.0.1 on 2024-02-08 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_avis_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biens',
            old_name='photos',
            new_name='image_principale',
        ),
        migrations.AddField(
            model_name='biens',
            name='etat',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('non_disponible', 'Non disponible')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='biens',
            name='image_facultative_1',
            field=models.ImageField(blank=True, null=True, upload_to='biens_photos/'),
        ),
        migrations.AddField(
            model_name='biens',
            name='image_facultative_2',
            field=models.ImageField(blank=True, null=True, upload_to='biens_photos/'),
        ),
        migrations.AddField(
            model_name='biens',
            name='image_facultative_3',
            field=models.ImageField(blank=True, null=True, upload_to='biens_photos/'),
        ),
        migrations.AddField(
            model_name='biens',
            name='image_facultative_4',
            field=models.ImageField(blank=True, null=True, upload_to='biens_photos/'),
        ),
        migrations.AlterField(
            model_name='biens',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
