# Generated by Django 5.0.1 on 2024-02-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_reservation_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_expiration_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='paiement_effectue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='biens',
            name='etat',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('non_disponible', 'Non disponible'), ('reservation_en_cours', 'reservation en cours')], default='disponible', max_length=20),
        ),
    ]
