# Generated by Django 5.0.1 on 2024-03-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_numero_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='numero_tel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
