# Generated by Django 5.0.1 on 2024-02-08 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_photos_biens_image_principale_biens_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biens',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
