# Generated by Django 5.0.1 on 2024-03-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_numero_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nom',
            field=models.CharField(max_length=35),
        ),
    ]
