# Generated by Django 5.0.1 on 2024-03-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biens',
            name='image_principale',
            field=models.ImageField(upload_to='media/biens_photos/'),
        ),
    ]
