# Generated by Django 5.0.1 on 2024-02-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_reservation_date_expiration_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biens',
            name='etat',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('non_disponible', 'Non disponible'), ('en_cours', 'En cours')], default='disponible', max_length=20),
        ),
    ]
