# Generated by Django 5.0.1 on 2024-03-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_biens_image_principale'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='biens',
            name='image_principale',
            field=models.ImageField(upload_to='biens_photos/'),
        ),
        migrations.AlterField(
            model_name='biens',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
