# Generated by Django 5.0.1 on 2024-02-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
